### ISSUE TITLE
coin-hive-stratum compile issue

### ISSUE THREAD

**Issue by QuantumLeaper** [cazala/coin-hive-stratum#1]
Hey there, I'm getting an issue when trying to run coin-hive-stratum:
`function createProxy(options = defaults) {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/coin-hive-stratum/bin/coin-hive-stratum:3:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
`

I took a look at coin-hive-stratum on line 3, but it just seems to be a require for the modules.

**Comment by QuantumLeaper** [comment]
This was corrected by reinstalling node!
