### ISSUE TITLE
miner connection error

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#11]
message from pool to miner:

 {"jsonrpc":"2.0","method":"job","params":{"blob":"0606e48f81cf05f2d216c4902828818b5bf52ceb3fa3952c79f8999bb573eb13bff7d0d13ee37600000000e99c66d89e2bab1fdd4563d0a5680c210f3df6ae7d84412f6b69bddbeeaa0ade0d","job_id":"O126cMb/mXHNXh/v/lS/a6etnKYI","target":"9bc42000","id":"3369af48-de91-4a4a-8387-dec574742bb0"}}

/usr/local/lib/node_modules/coin-hive-stratum/node_modules/ws/lib/WebSocket.js:355
      else throw new Error('not opened');
           ^

Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/coin-hive-stratum/node_modules/ws/lib/WebSocket.js:355:18)
    at sendToMiner (/usr/local/lib/node_modules/coin-hive-stratum/src/proxy.js:106:19)
    at Socket.<anonymous> (/usr/local/lib/node_modules/coin-hive-stratum/src/proxy.js:155:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)

**Comment by procloud** [comment]
perhaps need

if (connection.readyState === WebSocket.OPEN)

on line 105 of proxy.js in sendToMiner function
