### ISSUE TITLE
EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by Xuiquaxa** [cazala/coin-hive-stratum#175]
Im started but give this error
Error: listen EACCES 0.0.0.0:80                   
x                                xx proxy >     at Server.setupListenHandle [as _listen2] (net.js:1343:19)       x
x                                xx proxy >     at listenInCluster (net.js:1401:12)                              x
x                                xx proxy >     at Server.listen (net.js:1485:7)                                 x
x                                xx proxy >     at Proxy.listen (/home/***/node_modules/coin-hive-stratum

**Comment by sagarpatilaw18** [comment]
Maybe you are running this Linux machine where you don't have root access to run this application, try with sudo
