### ISSUE TITLE
cant find worker id

### ISSUE THREAD

**Issue by procloud** [cazala/coin-hive-stratum#22]
message from pool to miner:

 {"id":1,"jsonrpc":"2.0","error":{"code":-1,"message":"Unauthenticated"}}

/usr/local/lib/node_modules/coin-hive-stratum/src/proxy.js:139
        connection.workerId = data.result.id;
                                          ^

TypeError: Cannot read property 'id' of undefined
    at Socket.<anonymous> (/usr/local/lib/node_modules/coin-hive-stratum/src/proxy.js:139:43)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)

**Comment by procloud** [comment]
*this occurred almost immediately after a restart from a previously failure

**Comment by cazala** [comment]
Is this happening to you with version `1.1.2`?  cos that bug has been [fixed already](https://github.com/cazala/coin-hive-stratum/blob/master/src/proxy.js#L157-L165)
