### ISSUE TITLE
Syntax error v1.4.7

### ISSUE THREAD

**Issue by justnx** [cazala/coin-hive-stratum#52]
Code or dependecies or node version issue?

/usr/lib/node_modules/coin-hive-stratum/src/proxy.js:606
      wss.on("connection", async (ws, req) => {
                                                      ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/coin-hive-stratum/bin/coin-hive-stratum:3:21

**Comment by procloud** [comment]
looks like version issue, update npm

**Comment by korzhyk** [comment]
remove `async`.

**Comment by cazala** [comment]
oh, sorry for that 😅 that wasn't even needed there. Iit's removed in `v1.4.8`
