### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Thawwed** [cazala/coin-hive-stratum#55]
This is the error I'm getting when I try to run the command line

`
const createProxy = require("..");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
electroneum@localhost:~/electroneum-pool$
`

**Comment by cazala** [comment]
which version of node are you using?

**Comment by Thawwed** [comment]
0.10.25

**Comment by Thawwed** [comment]
I just tried 0.10.48 also. Same issue.

**Comment by Tr1NiT** [comment]
try this steps https://stackoverflow.com/questions/8191459/how-do-i-update-node-js/19584407#19584407

**Comment by cazala** [comment]
You need node 6+ to run this package
