### ISSUE TITLE
TypeError: Cannot set property '-1' of null

### ISSUE THREAD

**Issue by CineXMike** [cazala/coin-hive-stratum#58]
Hi,

Once in a while i get this error.

```
poolConnection.auths[rpcId] = connection;

TypeError: Cannot set property '-1' of null
    at minerMessageHandler (C:\Users\Administrator\Desktop\proxies\8895\node_modules\coin-hive-stratum\src\proxy.js:399:35)
    at loginDonationConnection (C:\Users\Administrator\Desktop\proxies\8895\node_modules\coin-hive-stratum\src\proxy.js:540:3)
    at options.donations.forEach.donation (C:\Users\Administrator\Desktop\proxies\8895\node_modules\coin-hive-stratum\src\proxy.js:671:13)
    at Array.forEach (<anonymous>)
    at WebSocketServer.wss.on (C:\Users\Administrator\Desktop\proxies\8895\node_modules\coin-hive-stratum\src\proxy.js:657:27)
    at emitTwo (events.js:126:13)
    at WebSocketServer.emit (events.js:214:7)
    at handleUpgrade (C:\Users\Administrator\Desktop\proxies\8895\node_modules\ws\lib\WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (C:\Users\Administrator\Desktop\proxies\8895\node_modules\ws\lib\WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (C:\Users\Administrator\Desktop\proxies\8895\node_modules\ws\lib\WebSocketServer.js:197:10)
[Nov 12th 01:26] Can't get rpcId, invalid pool connection
```
Greetings,
Mike

**Comment by CineXMike** [comment]
I only have it when i have allot of connections,
I cant even launch the server with 2600 connections.

**Comment by d-pelikhov** [comment]
+ 1
`/usr/local/lib/node_modules/minero/node_modules/coin-hive-stratum/src/proxy.js:353
poolConnection.auths[rpcId] = connection;
                            ^

TypeError: Cannot set property '-1' of null
at minerMessageHandler (/usr/local/lib/node_modules/minero/node_modules/coin-hive-stratum/src/proxy.js:353:35)
at loginDonationConnection (/usr/local/lib/node_modules/minero/node_modules/coin-hive-stratum/src/proxy.js:497:3)`

**Comment by cazala** [comment]
The fix for this will be included in v2
