### ISSUE TITLE
v1.1.0

### ISSUE THREAD

**Issue by nbnfybr** [cazala/coin-hive-stratum#6]
/root/.nvm/versions/node/v8.6.0/lib/node_modules/coin-hive-stratum/src/proxy.js:208
      wss.on('connection', (ws) => {
      ^

ReferenceError: wss is not defined
    at Object.listen (/root/.nvm/versions/node/v8.6.0/lib/node_modules/coin-hive-stratum/src/proxy.js:208:7)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.6.0/lib/node_modules/coin-hive-stratum/bin/coin-hive-stratum:32:7)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

**Comment by zolter** [comment]
Edit file "coin-hive-stratum/src/proxy.js"

`     if (options.path) {
        let wss = new WebSocket.Server({ path: options.path, port: +port });
      } else {
        let wss = new WebSocket.Server({ port: +port });
      }`

replace "let" to "var"

**Comment by zolter** [comment]
#7
