### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by dspstudio** [cazala/coin-hive-stratum#82]
Im using fresh install of ubuntu 14 Linux server 2.6.32-042stab117.14 #1 SMP Tue Aug 30 17:12:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

```
root@server:~/coin-hive-stratum# npm install -g coin-hive-stratum
npm http GET https://registry.npmjs.org/coin-hive-stratum
npm http 304 https://registry.npmjs.org/coin-hive-stratum
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/types/node
npm http GET https://registry.npmjs.org/types/ws
npm http GET https://registry.npmjs.org/pmx
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/watch
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/pmx
npm http 304 https://registry.npmjs.org/watch
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/ws
npm http 404 https://registry.npmjs.org/types/ws
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab117.14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "coin-hive-stratum"
npm ERR! cwd /root/coin-hive-stratum
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab117.14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "coin-hive-stratum"
npm ERR! cwd /root/coin-hive-stratum
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/coin-hive-stratum/npm-debug.log
npm ERR! not ok code 0

```

**Comment by CineXMike** [comment]
First run npm update then npm install coin-hive-stratum inside the folder where your startscript is located

**Comment by dspstudio** [comment]
same 404 
```
root@server:~# cd coin-hive-stratum/
root@server:~/coin-hive-stratum# npm update
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/watch
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/pmx
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/%40types/node
npm http GET https://registry.npmjs.org/%40types/ws
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/watch
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/pmx
npm http 304 https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/minimist
npm http 404 https://registry.npmjs.org/%40types/ws
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab117.14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! cwd /root/coin-hive-stratum
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 404 https://registry.npmjs.org/%40types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab117.14
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! cwd /root/coin-hive-stratum
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/coin-hive-stratum/npm-debug.log
npm ERR! not ok code 0

```
