### ISSUE TITLE
Apache + node

### ISSUE THREAD

**Issue by mport88** [cazala/coin-hive-stratum#96]
Hello,
I have a vps + ssl + apache and I use the following code:
```
const Proxy = require("coin-hive-stratum");
const domain = "MY_DOMAIN_HERE"
const proxy = new Proxy({
  host: "pool.supportxmr.com",
  port: 3333,
  key: require("fs").readFileSync("/etc/letsencrypt/live/" + domain + "/privkey.pem"),
  cert: require("fs").readFileSync("/etc/letsencrypt/live/" + domain + "/fullchain.pem"),
});
proxy.listen(443);
```

However, in the logs I have an error:
```
2017-12-10 22:03: pool connection error (a9dfdd9e-d1d4-459a-b037-6r056959b120): invalid_site_key
2017-12-10 22:03: proxy error: undefined
2017-12-10 22:15: Error: listen EADDRINUSE :::443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Proxy.listen (/tratata/node_modules/coin-hive-stratum/build/Proxy.js:189:25)
    at Object.<anonymous> (/tratata/proxy_secure.js:9:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

```
I think that the issue in Apache. Can you tell me please how to solve my issue?
I will be grateful for any help.
p.s
 I tried to specify a different port - everything worked, but on the site where the miner is installed in the dev.tool "Network" tab is written - "MY_DOMAIN - pending" and mining does not work.

**Comment by cazala** [comment]
The problem is you already have something listening on por 443. You can always change that port though to a different one, like this (last line):

```
proxy.listen(3333);
```

Now you can access your proxy like this `wss://yourdomain.com:3333`.

If you want to use the port 443 (which is the one used by the browser by default) you will need to configure your apache server to foward the websocket connections from `443` to `3333` in this case. I dunno how to do that tho, I never used apache.
